spring.application.name=codeValut

jwt.secret=your-very-long-secret-key-at-least-256-bits-for-hs256-algorithm-change-this
jwt.expiry=86400000

# PostgreSQL Database Connection Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/codeVault
spring.datasource.username=postgres
spring.datasource.password=jodx
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
